apiVersion: apps/v1
kind: Deployment
metadata:
  name: yte-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yte-demo-app
  template:
    metadata:
      labels:
        app: yte-demo-app
    spec:
      containers:
        - name: yte-demo-app
          image: yte-demo-app-image:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP



---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deployment-redis
  name: svc-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      nodePort: 32666
  selector:
    app: deployment-redis
  type: NodePort